<?php
/*
Copyright 2017 Oscar.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

namespace LAMgmt;

use \LAMgmt\Util\Utils;

?>
            <!-- Right side column. Contains the navbar and content of the page -->
            <div class="content-wrapper">
                <!-- Content Header (Page header) -->
                <section class="content-header">

                </section>

                <!-- Main content -->
                <section class="content">

                    <div class="error-page">
                        <h2 class="headline text-red"> 500</h2>
                        <div class="error-content">
                            <h3><i class="fa fa-warning text-red"></i> Oh, vaja! Alguna cosa no va bé.</h3>
                            <p>
                                Estem treballant en solucionar el problema.
                                Mentrestant, pots seleccionar una altra opció del menú o tornar al <a href="<?php echo Utils::createLink("home"); ?> ">inici</a>.
                            </p>
                            <?php
                                if (isset($extra))
                                {
                            ?>
                                <div class="box box-warning collapsed-box">
                                  <div class="box-header with-border tech-info">
                                    <!-- <h3 class="box-title">Informació tècnica</h3> -->
                                    Informació tècnica
                                    <div class="box-tools pull-right tech-info">
                                      <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i></button>
                                    </div><!-- /.box-tools -->
                                  </div><!-- /.box-header -->
                                  <div class="box-body">
                                    <?php 
                                        $actual_link = (isset($_SERVER['HTTPS']) ? "https" : "http") . "://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";
                                        echo "URL: $actual_link<br/>";
                                        echo "Missatge: ".$extra['message'];
                                    ?>
                                  </div><!-- /.box-body -->
                                </div>
                            <?php
                                }
                            ?>                            
                        </div><!-- /.error-content -->
                    </div><!-- /.error-page -->
                </section><!-- /.content -->
            </div><!-- /.content-wrapper -->