<?php
/*
 * Copyright 2017 Oscar.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
?>
<!-- Right side column. Contains the navbar and content of the page -->

<div class="content-wrapper">

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            <?php echo ($edit ? "Editar " : "Nou ") ?> alumne
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-users"></i> Inici</a></li>
            <li><a href="#">Alumnes</a></li>
            <li class="active"><?php echo ($edit ? "Editar " : "Nou ") ?> alumne</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <form action="#" method="post">
            <div class="row">
                <div class="col-md-6">
                    <!-- Default box -->
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Dades personals</h3>
                        </div><!-- /.box-header -->
                        <div class="box-body">
                            <?php echo \LAMgmt\Util\Utils::getPersonalDataForm("alumne",$alumneValues); ?>
                        </div><!-- /.box-body -->
                    </div><!-- /.box -->
                </div><!-- /.col-md-6 -->
                <div class="col-md-6">
                    <!-- Contactes box -->
                    <?php /*$contactesAlumneValues[0]*/ ?>
                    <div class="box box-warning">
                        <div class="box-header with-border">
                            <h3 class="box-title">Contactes</h3>
                        </div><!-- /.box-header -->
                        <?php echo \LAMgmt\Util\Utils::getContacteTabsIfNecessary($contactesAlumneValues); ?>
                        <div class="box-body">
                            <?php 
                                $items = count($contactesAlumneValues);
                                if ($items == 0) { 
                                    $items = 1; 
                                } else {
                                    if ($items > 1) {
                                        echo '<div class="tab-content">';
                                    }
                                }
                                $i = 0;
                                $first = true;
                                while ($i < $items) {
                                    if (count($contactesAlumneValues) > 1) {
                                        if ($first == true) {
                                            echo '<div id="cte' . $contactesAlumneValues[$i]['id'] . '" class="tab-pane fade in active">';
                                            $first = false;
                                        } else {
                                            echo '<div id="cte' . $contactesAlumneValues[$i]['id'] . '" class="tab-pane fade in">';
                                        }
                                    }
                                    $relacio = "";
                                    if (count($contactesAlumneValues) > 0) {
                                        $relacio = $contactesAlumneValues[$i]['relacio'];
                                        $relacioAltres = $contactesAlumneValues[$i]['relacio_altres'];
                                    }
                            ?>
                            <label>Relació amb l'alumne</label>
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-6 noPaddingRight">
                                        <select class="form-control" name="contacte[relacio]" id="relacio">
                                            <option <?php echo ($relacio == "P" ? "selected" : "") ?> value="P">Pare</option>
                                            <option <?php echo ($relacio == "M" ? "selected" : "") ?> value="M">Mare</option>
                                            <option <?php echo ($relacio == "G" ? "selected" : "") ?> value="G">Germà</option>
                                            <option <?php echo ($relacio == "I" ? "selected" : "") ?> value="I">Avi</option>
                                            <option <?php echo ($relacio == "A" ? "selected" : "") ?> value="A">Àvia</option>
                                            <option <?php echo ($relacio == "L" ? "selected" : "") ?> value="L">Altres</option>
                                        </select>
                                    </div>
                                    <div class="col-md-6 padLeft5">
                                        
                                        <input <?php echo "value='$relacioAltres'" ?> id="relacio_altres" name="contacte[relacio_altres]" type="text" class="form-control" placeholder="Altre relació" <?php echo ($relacioAltres != "") ? "" : "disabled" ?>>
                                    </div>
                                </div>
                            </div>                    
                            <?php 
                                    if (count($contactesAlumneValues) > 0) {
                                        echo \LAMgmt\Util\Utils::getPersonalDataForm("contacte",$contactesAlumneValues[$i],false);
                                    } else {
                                        echo \LAMgmt\Util\Utils::getPersonalDataForm("contacte",null,false);
                                    }
                                    $i++;
                                    /* close <div id="xxx" class="tab-pane fade in"> */
                                    if (count($contactesAlumneValues) > 1) {
                                        echo "</div>";
                                    }
                                }
                                /* close <div class="tab-content"> */
                                if (count($contactesAlumneValues) > 1) {
                                    echo "</div>";
                                }
                            ?>
                        </div><!-- /.box-body -->
                    </div><!-- /.box -->
                </div><!-- /.col-md-6 -->            
            </div><!-- /.row -->
            <div class="row">
                <div class="col-md-12">
                    <input type="submit" name="guardar" value="Guardar" class="btn btn-primary btn-lockwidth center-block" />
                </div>
            </div>
        </form>
    </section><!-- /.content -->
</div><!-- /.content-wrapper -->