<?php
/*
 * Copyright 2017 Oscar.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
?>
<!-- Right side column. Contains the navbar and content of the page -->
<div class="content-wrapper">

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Alumnes
            <small>manteniment</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-users"></i> Inici</a></li>
            <li><a href="#">Alumnes</a></li>
            <li class="active">Manteniment</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <!-- Default box -->
                <div class="box box-primary">
                    <!-- <div class="box-header with-border">
                        <h3 class="box-title">Alumnes</h3>
                    </div><!-- /.box-header -->
                    <div class="box-body">

                        <table id="alumnes" class="table table-bordered table-hover" cellspacing="0" width="100%">
                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Primer Cognom</th>
                                    <th>Segon Cognom</th>
                                    <th>Nom</th>
                                    <th>Mòbil</th>
                                    <th>Telèfon</th>
                                    <th>Email</th>
                                    <th>D. Naixement</th>
                                    <th>D. Ingrés</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>

                    </div><!-- /.box-body -->
                </div><!-- /.box -->
            </div><!-- /.col-md-12 -->
        </div><!-- /.row -->
    </section><!-- /.content -->
</div><!-- /.content-wrapper -->